#!/bin/bash
first_num=$RANDOM
second_num=$RANDOM
first_sqrt=$(echo "sqrt($first_num)" | bc)
second_sqrt=$(echo "sqrt($second_num)" | bc)
echo "The first random number generated is $first_num"
echo "The square root is $first_sqrt"
echo "The second random number generated is $second_num"
echo "The square root is $second_sqrt"
echo "The sum of their square root is $((first_sqrt + second_sqrt))"
